version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/다운로드/im-sprint-practice-deploy-master

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      runas: root
  AfterInstall:
    - location: scripts/initialize.sh
      runas: root
  ApplicationStart:
    - location: scripts/start.sh
      runas: root